---
name: Run tests

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          bb: 1.3.186

      - name: lint categories
        run: bb lint_tags.bb
